### ISSUE TITLE
New version needs to be released

### ISSUE THREAD

**Issue by nwoltman** [htmllint/htmllint-cli#29]
It has been over a year since the last version of `htmllint-cli` was released. There have been some important improvements since then (such as support for the latest version of `htmllint`) so it would be helpful to have these changes available on `npm`.

**Comment by fchiumeo** [comment]
the project became obsolete ?

**Comment by mlochbaum** [comment]
It's released. Sorry to leave you hanging so long.

**Comment by nwoltman** [comment]
Great, thanks @mlochbaum!
